export const data = [
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 1,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 2,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 2',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 3,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 3',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 4,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 4',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 5,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 5',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 6,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 6',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 7,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 7',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 8,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 9,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 10,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 11,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 12,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 13,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 14,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 15,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 16,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 17,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 18,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 19,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 20,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
    {
        amount_max: 10000,
        amount_min: 1000,
        description_full: 'Полное описание фонда 1',
        description_short: 'Кароткое описание фонда 1',
        id: 21,
        image: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/check.svg',
        name: 'Фонд 1',
    },
];
